### ISSUE TITLE
Les barres de progressions des milestones sont fidèles au vrai pourcentage

### ISSUE THREAD

**Issue by hugo-perier** [Kozea/gibolt#100]
Aujourd'hui sur la page **My urgency**, toutes les barres de progressions sont à 0%.

**Comment by SamR1** [comment]
Il s'avère qu'il s'agit du fonctionnement normal: le calcul est correct, les tickets lorsqu'ils sont fermés via **Gibolt** n'ont plus de label **Urgent** et donc ne sont plus pris en compte dans le calcul de la progression dans **My Urgency**
A voir si le clôture d'un ticket via Gibolt doit supprimer systématiquement le label **Urgent** => ping @yobuntu

**Comment by yobuntu** [comment]
Le pourcentage d'avancement est en effet calculé par le calcul tickets fermé/total tickets * 100.

Mais basé sur les tickets qui correspondent au filtre utilisé.
C'était très pratique pour le fonctionnement en sprint, mais ça n'a en effets plus beaucoup de sens maintenant.
