### ISSUE TITLE
L'association des cercles sur les milestones est améliorée

### ISSUE THREAD

**Issue by hugo-perier** [Kozea/gibolt#115]
Quand un cercle est déjà associé et qu'on veut en ajouter un autre on est obligé de re-cliquer sur le premier sinon il est remplacé.

**Comment by SamR1** [comment]
Dans le cas des selects multiple, il faut utiliser 'Ctrl + clic' pour ajouter un autre label

EDIT : Après échanges: proposition d'utiliser react-select qui serait + _user-friendly_
https://jedwatson.github.io/react-select/
