### ISSUE TITLE
On peut clore une milestone

### ISSUE THREAD

**Issue by Le-Stagiaire** [Kozea/gibolt#129]
Et au passage enlever les labels de cercle sur la milestone qu'on ferme

**Comment by SamR1** [comment]
comme vu ensemble:
* écran **Timeline**: on peut fermer la milestone (sans modifier les cercles associés)
* écran **Circle**: on peut fermer et dissocier la milestone du cercle affiché (pas d'impact sur les autres cercle associés)

(la fonctionnalité de dissociation n'est pour le moment pas active sur l'écran de génération du rapport)
