### ISSUE TITLE
La courbe des indicateurs est mise à jour seulement lorsqu'on rentre une nouvelle valeur

### ISSUE THREAD

**Issue by Le-Stagiaire** [Kozea/gibolt#144]

**Comment by yobuntu** [comment]
wont-fix

**Comment by Le-Stagiaire** [comment]
Tu peux me faire ca asap stp ? j'suis dans le cercle marco

**Comment by yobuntu** [comment]
c'est impossible.

**Comment by Le-Stagiaire** [comment]
Et bien rends le possible, je suis sûr que tu en es capable

**Comment by yobuntu** [comment]
Bien Clément on va faire ça ASAP…

**Comment by Le-Stagiaire** [comment]
Merci c'est tout ce que je voulais, voir ce ticket ouvert en bientôt, tu vois on peut communiquer sereinement :)

**Comment by SamR1** [comment]
ce qui a été mis en place:
* tant que la dernière valeur n'est pas renseignée, on affiche la valeur précédente 
![capture du 2018-03-28 10-51-43_resized](https://user-images.githubusercontent.com/3525167/38019069-e9ae83ce-3276-11e8-9b85-cc4d826457a4.png) 
![capture du 2018-03-28 10-52-21_resized](https://user-images.githubusercontent.com/3525167/38019059-e64c621e-3276-11e8-8ac9-dbc6436ed122.png)
* les valeurs manquantes sont extrapolées
![capture du 2018-03-28 10-49-57_resized](https://user-images.githubusercontent.com/3525167/38019243-5a3d994a-3277-11e8-8793-0277cd84dbc8.png)
![capture du 2018-03-28 10-49-57_resized2](https://user-images.githubusercontent.com/3525167/38019246-5d538d56-3277-11e8-9fe7-1688d8ba02e8.png)

**Comment by yobuntu** [comment]
Ça me semble être exactement ce dont on a parlé
