### ISSUE TITLE
L'idée d'intégrer la gestion des hooks dans Gibolt est acceptée ou refusée

### ISSUE THREAD

**Issue by arthru** [Kozea/gibolt#15]

**Comment by liZe** [comment]
C'est pas déjà possible avec GitHub ?

**Comment by arthru** [comment]
Si mais ça n'a pas l'air implémenté dans gibolt...

**Comment by yobuntu** [comment]
Vu la tournure prise par gibolt, je pense que l'outil va plus vers la gestion de projet, et idéalement les liens vers github ou d'autre dépôt de code seraient des plugins ça sera surement le moment d’intégrer les mise a jour via des hook plutôt que d'aller régulièrement vérifier l'état de github
