### ISSUE TITLE
Les membres du groupe Kozea/coders ne peuvent plus modifer l'holacratie

### ISSUE THREAD

**Issue by yobuntu** [Kozea/gibolt#182]
Certains anciens salariés de Kozea font encore partie du groupe Kozea/Coders afin de pouvoir maintenir certains projets libres de Kozea. Ces dernier (dont je fait partie) ont un accès complet en lecture et modification à l'organisation de l'holacratie de Kozea.

**Comment by cmigazzi** [comment]
Merci @yobuntu ! C'est corrigé via  99d0d19
