### ISSUE TITLE
Les boutons de validation des formulaires n'affichent plus de libellé en anglais

### ISSUE THREAD

**Issue by gentooboontoo** [Kozea/gibolt#185]
Les boutons de validation affichent actuellement _Submit query_ (au moins sur Firefox) :

![image](https://user-images.githubusercontent.com/137324/200324840-9b417510-53dc-4123-8736-8d779d48f1f7.png)

Ils devraient afficher un texte en français de type _Enregistrer_ ou _Valider_ par exemple. 

Ils apparaissent notamment dans les formulaires d'édition des réunions ou d'un rôle de cercle (il y en a peut-être ailleurs).

- [x] @annabellou quel libellé serait le plus approprié ?
- [x] identifier le problème 
- [x] ajouter un lien dans le ticket vers une page de documentation l'expliquant
- [x] rechercher tous les boutons de validation présentant le problème dans le code
- [x] corriger l'intitulé

**Comment by ibtihalaa** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit

**Comment by ibtihalaa** [comment]
>@annabellou quel libellé serait le plus approprié ? 

Comme vu avec @annabellou on va utiliser `Valider` comme libellé
