### ISSUE TITLE
Nouveau style

### ISSUE THREAD

**Issue by liZe** [Kozea/gibolt#19]

**Comment by annabellou** [comment]
Quelques visuels sont dispos sur le drive : https://drive.google.com/open?id=0B62Ll0D3yTZ6QmkwX3FkVlFxa2c

Les couleurs ne sont pas définitives, ni la typo d'ailleurs, c'était plus pour avoir une idée de la mise en place des éléments. 

Si vous avez des idées / commentaires, ce serait cool de partager !
