### ISSUE TITLE
La nouvelle vue des projets correspond aux attentes

### ISSUE THREAD

**Issue by liZe** [Kozea/gibolt#29]

**Comment by yobuntu** [comment]
afin d'en arriver là je propose d'organiser une réunion avec quelques personnes du cercle commercial sur les thèmes suivants:
 - Pourquoi une vue projet
   - Qu'est-ce qu'un projet en holacratie
   - A quoi va servir la vue projet
- Parcours de la vue projet existante
  - chacun liste 3 point positifs et 3 points négatifs
- Trouver comment amélioré la vue:
  - focus sur l'élimination des point négatifs qui reviennent le plus souvent.
  - création d'un «wireframe» de la vue projet.

**Comment by yobuntu** [comment]
obsolète
