### ISSUE TITLE
Créer des fiches de suivi des tickets assignés par personne

### ISSUE THREAD

**Issue by liZe** [Kozea/gibolt#4]
Cela pourrait par exemple servir à imprimer des fiches de suivi de temps.

**Comment by liZe** [comment]
Exemple :

# Guillaume Ayoub

## Mai 2015
- Hydra (67%)
  - #XXXXX
  - #XXXXX
- Gibolt (33%)
  - #XXXXX

## Avril 2015
- Hydra (67%)
  - #XXXXX
  - #XXXXX
- Gibolt (33%)
  - #XXXXX

**Comment by yobuntu** [comment]
c'est fait
