### ISSUE TITLE
L'idée d'intégrer un kanban dans Gibolt est acceptée ou refusée

### ISSUE THREAD

**Issue by cristen** [Kozea/gibolt#40]
Ça serait super cool  et je m’en servirais tous les jours !

![image](https://cloud.githubusercontent.com/assets/4291963/20628820/91696950-b328-11e6-85b5-5bba980a8f51.png)

**Comment by hugo-perier** [comment]
Oui sur cette page nous en aurons besoin :
https://drive.google.com/open?id=0B2_zOv2suKd-b290aThLb1VpSkI1Vl9Fd2VySmhSRllaTE9J
