### ISSUE TITLE
Les fonctionnalités de la nouvelle plateforme sont listées

### ISSUE THREAD

**Issue by liZe** [Kozea/gibolt#43]

**Comment by JordanKozea** [comment]
Il serait nécessaire de pouvoir fermer ou créer des tickets directement sur Gibolt.
Il serait intéressant de visualiser ses nouveaux tickets.
Une section emploi du temps peut être envisageable, cette section permettrait de pouvoir classer ses tickets en fonction du temps (système de drag and drop).
Le besoin réside ici dans un aspect pratique qui viserait à empêcher les utilisateurs de Gibolt d'alterner entre différentes plateformes après chaque clôture de tickets. L'équipe développement semble particulièrement intéressée par cette fonctionnalité.

**Comment by JordanKozea** [comment]
Il est attendu de pouvoir mieux entrevoir les différents rôles présents dans chaque cercle ainsi que la personne à qui ils sont attribués selon le projet.

- L'administrateur de chaque cercle a besoin d'un accès rapide au détail des rôles du cercle lors des réunions de gouvernance et de triage.
- Une personne qui crée un ticket a besoin d'accéder à une liste de l'ensemble des rôles pour savoir à quel rôle assigner son ticket et quelle personne fait ce rôle.
- Une personne appartenant à un cercle doit pouvoir, si besoin est, filtrer et grouper les tickets selon le cercle auquel ils appartiennent afin de n'afficher que ceux nécessaires.
- Vue d'ensemble des différents rôles et cercles, peut-être sous forme d'un schéma en cercle.
- Une personne souhaitant créer un projet spécifique doit pouvoir vérifier que cette spécificité ne fait pas partie des prérogatives d'un rôle déjà existant

**Comment by JordanKozea** [comment]
Il a été demandé à ce que Gibolt prenne en compte la gestion des comptes rendu dans le sens où ces derniers pourraient être accessibles directement sur Gibolt, organisé selon le cercle et le type de réunion

- L'administrateur de chaque cercle a besoin d'un accès rapide aux comptes-rendus des différentes réunions de gouvernance et de triage pour connaître les points déjà abordés
- Une personne ayant une proposition ou une tension à mettre en avant au cours d'une réunion peut accéder rapidement aux comptes rendus antérieurs afin d'établir si les points ont déjà été abordés.
- Une personne peut avoir besoin d'un accès rapide à un compte rendu afin de reprendre connaissance de la solution ayant été adoptée en réunion face à une tension précise.
- l'administrateur peut avoir besoin de se renseigner sur un sujet déjà abordé sans pour autant connaître le compte rendu concerné : il serait donc pratique de pouvoir rechercher un compte rendu en fonction de ce qu'il contient

**Comment by JordanKozea** [comment]
Enfin, il ressort comme besoin primordial d'avoir une meilleure vision globale des différentes tâches à effectuer selon le projet (la Timeline présente jusqu'alors n'étant pas visuellement la plus adaptée).
Pour une meilleure visibilité et prise en considération des tâches spécifiques à mettre en avant

- Une personne désirant s'organiser dans ses tâches au cours d'une période de plusieurs semaines voire de plusieurs mois a besoin d'une vision d'ensemble des différentes tâches assignées à un projet sur de longues périodes. 
- La vision des tickets doit être claire et organisée, c'est à dire qu'une personne doit avoir la possibilité de filtrer les tickets en fonction du cercle concerné.
- Une personne doit pouvoir filtrer les tickets selon leur priorisation.
- Une personne doit pouvoir voir de manière claire si des tickets, même non urgents, deviennent prioritaire dû à l'approche de la date butoir de la milestone concernée.
- Aussi, il serait apprécié de pouvoir filtrer les milestones en fonction des cercles auxquels ils s'appliquent (DevOps, MarCo).
- Il serait préférable de définir un ordre de triage pour les milestones. Celles-ci seraient triées par ordre d'importance (le nombre de milestones contenues) mais également selon leur mise à jour (actions sur le milestone).
- Un indicateur sera également présent pour informer de la fermeture récente, de l'ouverture et du stand by d'une milestone.
- L'affichage sera prioritaire aux milestones qui ont été fermées récemment et celles qui sont ouvertes et actives. Un chiffre correspondant à ces dernières sera affiché pour chaque dépot. Les autres étant affichées dans un sous-menus car moins importante.
- Les milestones fermées depuis un certain temps (sûrement 2 semaines) ne seront pas affichées sur Gibolt.
