### ISSUE TITLE
Le design de l'API est validé

### ISSUE THREAD

**Issue by Romlie** [Kozea/gibolt#50]
https://github.com/Kozea/gibolt/wiki/The-Gibolt-API

**Comment by liZe** [comment]
- [x] Pour les dépôts (et certains autres comme les tickes), choisissez votre identifiant (`id` ou `name`) et utilisez-le comme identifiant dans vos URLs.
- [x] Ne commencez pas vos URLs par une variable ou vous risquez d'avoir des collisions.
- [x] Ne gardez pas les champs `html_url` et `url` qui amènent sur GitHub.
- [x] Utilisez des identifiants cohérents dans vos URLs (`:name`, `:repo`).
- [x] Supprimez des champs dans `/tickets` (et dans la plupart de vos `GET` sur des collections).
- [x] Ne mettez pas les données de l'assignee dans le `PUT`/`POST` des tickets.
- [x] Mettez l'identifiant du ticket dans l'URL de la liste des commentaires.
- [x] Utilisez des nombres muets et pas le nom pour identifier les cercles.
- [x] Ne mettez pas les données du cercle dans le `POST` des rapports.
- [x] Utilisez des nombres muets et pas le nom pour identifier les rôles.
- [x] Mettez l'identifiant du cercle dans les routes des rapports.
- [x] Ajoutez des `DELETE` au moins pour les cercles et les rôles.

**Comment by Romlie** [comment]
- Pour les dépôts (et certains autres comme les tickes), choisissez votre identifiant (`id` ou `name`) et utilisez-le comme identifiant dans vos URLs.  :white_check_mark:
- Ne commencez pas vos URLs par une variable ou vous risquez d'avoir des collisions.   :white_check_mark:
- Ne gardez pas les champs `html_url` et `url` qui amènent sur GitHub.  :white_check_mark:
- Utilisez des identifiants cohérents dans vos URLs (`:name`, `:repo`).
- Supprimez des champs dans `/tickets` (et dans la plupart de vos `GET` sur des collections).
- Ne mettez pas les données de l'assignee dans le `PUT`/`POST` des tickets.
- Mettez l'identifiant du ticket dans l'URL de la liste des commentaires.
- Utilisez des nombres muets et pas le nom pour identifier les cercles.
- Ne mettez pas les données du cercle dans le `POST` des rapports.
