### ISSUE TITLE
Les sources de données sont documentées

### ISSUE THREAD

**Issue by liZe** [Kozea/gibolt#51]

**Comment by Romlie** [comment]
**Repositories**

| Name  | Data Sources | 
| ------------- | ------------- | 
| List repositories | GiTHUB API | 
| Get a single repository | GITHUB API  |

**Milestones**

| Name  | Data Sources | 
| ------------- | ------------- | 
| List milestones | GITHUB API | 
| Get a single milestone | GITHUB API   |
| Update a single milestone | GITHUB API   |
| Create a single milestone | GITHUB API   |

**Tickets**

| Name  | Data Sources | 
| ------------- | ------------- | 
| List tickets | GITHUB API | 
| Get a single ticket | GITHUB API   |
| Update a single ticket | GITHUB API   |
| Create a single ticket | GITHUB API   |

**Comments**

| Name  | Data Sources | 
| ------------- | ------------- | 
| List ticket's comments | GITHUB API | 
| Get a single ticket's comments | GITHUB API   |

**Labels**

| Name  | Data Sources | 
| ------------- | ------------- | 
| List labels | GITHUB API | 
| Get a single label | GITHUB API   |
| Update a single label | GITHUB API   |
| Create a single label | GITHUB API   |
| Delete a single label | GITHUB API   |

**Users**

| Name  | Data Sources | 
| ------------- | ------------- | 
| List users | GITHUB API | 
| Get a single user | GITHUB API |

**Circles**

| Name  | Data Sources | 
| ------------- | ------------- | 
| List circles | DATABASE | 
| Get a single circle | DATABASE  |
| Delete a single circle | DATABASE  |

**Roles**

| Name  | Data Sources | 
| ------------- | ------------- | 
| List roles | DATABASE | 
| Get a single role | DATABASE  |
| Update a single role | DATABASE  |
| Create a single role | DATABASE  |
| Delete a single role | DATABASE  |

**Reports**

| Name  | Data Sources | 
| ------------- | ------------- | 
| List reports | DATABASE | 
| Get a single report | DATABASE  |
| Update a single report | DATABASE  |
| Create a single report | DATABASE  |
| Delete a single report | DATABASE  |
