### ISSUE TITLE
Le modèle de la base de données est réalisé

### ISSUE THREAD

**Issue by liZe** [Kozea/gibolt#52]

**Comment by Romlie** [comment]
![database_diagram](https://cloud.githubusercontent.com/assets/25310926/26201267/70d1637c-3bd2-11e7-9edc-417241e3f572.png)

**Comment by SamR1** [comment]
Mise à jour du modèle de la base de données :
![modele_donnees](https://user-images.githubusercontent.com/3525167/33949964-5cfcecb0-e02b-11e7-89bc-86596638651e.png)
Lien du fichier: [modèle_données.graphml](https://drive.google.com/a/kozea.fr/file/d/17THy24HJMGa4ESkjBYADzPTTxdNJIVi_/view?usp=sharing) (éditable avec [yEd](https://www.yworks.com/products/yed))

**Comment by SamR1** [comment]
Mise à jour suite PR https://github.com/Kozea/gibolt/pull/96
Ajout du champ **is_active** dans la table **Circle**
![modele_donnees](https://user-images.githubusercontent.com/3525167/34871858-583b4af2-f78f-11e7-8904-4d722c7ba216.png)

**Comment by SamR1** [comment]
Last versions on [Wiki](https://github.com/Kozea/gibolt/wiki/The-Gibolt-Database)
