### ISSUE TITLE
Le site est stable en production

### ISSUE THREAD

**Issue by liZe** [Kozea/gibolt#54]
Le site en production tombe régulièrement depuis quelques temps. Lors du développement des nouvelles fonctionnalités, l'erreur a été assez facile à reproduire, quasiment à chaque fois que le site redémarre suite à la modification du code.

**Comment by yobuntu** [comment]
ça doit être tout bon maintenant, et si l'erreur vient le github, on devrait être au courant, plus qu'a mettre en prod
