### ISSUE TITLE
Il est possible de voir la liste de personnes dans un cercle

### ISSUE THREAD

**Issue by yobuntu** [Kozea/gibolt#64]
c'est à dire la liste des personnes energisant au moins un des rôles du cercle

**Comment by SamR1** [comment]
@yobuntu: Proposition/Actions réalisées:
* affichage de la liste des cercles, via la route `/circles'
![capture du 2017-12-14 17-35-00](https://user-images.githubusercontent.com/3525167/34003362-6098e4bc-e0f5-11e7-8c9e-16c68efb3a09.png)

* affichage du détail du cercle avec la liste des rôles en cliquant sur le cercle
la description du cercle (raison d'être, domaines, recevabilités) peut être affiché/masqué
![capture du 2017-12-14 17-38-52](https://user-images.githubusercontent.com/3525167/34003494-ae39126e-e0f5-11e7-9deb-ccc2a9186eee.png)
![capture du 2017-12-14 17-34-34](https://user-images.githubusercontent.com/3525167/34003390-772150de-e0f5-11e7-9896-05f496565699.png)

**Comment by SamR1** [comment]
Mise à jour:
* ajout de du nom du cercle parent
* ajout des certains boutons pour les CRUD Cercles (cf. https://github.com/Kozea/gibolt/issues/62) et Rôles (cf. https://github.com/Kozea/gibolt/issues/63)

![capture du 2017-12-18 10-01-43](https://user-images.githubusercontent.com/3525167/34097948-18c00150-e3db-11e7-8b36-76ca11447fd4.png)
![capture du 2017-12-18 10-02-11](https://user-images.githubusercontent.com/3525167/34097957-1e57880e-e3db-11e7-8bb4-acd8c25c3263.png)

**Comment by yobuntu** [comment]
Lors de la création des rapport, pour générer un fiche de présence.
