### ISSUE TITLE
La branche api-refractor est «mergée»

### ISSUE THREAD

**Issue by yobuntu** [Kozea/gibolt#78]
l'API définit dans le fichier backend/routes/___init__.py fonctionne à iso-fonctionnalité avec la version actuellement en production

**Comment by SamR1** [comment]
une première PR est ouverte : https://github.com/Kozea/gibolt/pull/79

**Comment by SamR1** [comment]
une PR concernant les tickets est ouverte : https://github.com/Kozea/gibolt/pull/81
