### ISSUE TITLE
On peut afficher les commentaires des tickets

### ISSUE THREAD

**Issue by yobuntu** [Kozea/gibolt#82]

**Comment by SamR1** [comment]
Affichage des commentaires en lecture seule (pas de pagination, le nombre de commentaires étant en général limité)
![capture d ecran de 2017-12-12 11-11-36](https://user-images.githubusercontent.com/3525167/33879824-e42e1602-df2f-11e7-9a15-57117370f65c.png)


Si une erreur se produit lors de la récupération des commentaires, les tickets sont quand même affichés et les erreurs rencontrées affichées en haut de la page
![capture d ecran de 2017-12-12 11-16-15](https://user-images.githubusercontent.com/3525167/33879230-198a08bc-df2e-11e7-8e0a-f48ae36bc61d.png)

**Comment by SamR1** [comment]
affichage des commentaires séparément (un bouton pour afficher le body, un bouton pour afficher les commentaires): 
![capture d ecran de 2017-12-12 12-45-57](https://user-images.githubusercontent.com/3525167/33883061-983bfea2-df3a-11e7-92e9-fee0b0b40600.png)
